#!/bin/sh
#
# Assumes pm-hibernate, pm-suspend, reboot, poweroff can be executed with
# NOPASSWD.
# For example, add the following to visudo to enable executing pm-hibernate
# without password:
#
#     username ALL=(ALL)NOPASSWD:/usr/sbin/pm-hibernate.

case "$1" in
  lock)
    i3lock -c 000000
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    sudo pm-suspend | i3lock -c 000000
    ;;
  hibernate)
    sudo pm-hibernate
    ;;
  reboot)
    sudo reboot
    ;;
  shutdown)
    sudo poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac

exit 0
